
all: run

run: 
	cargo run

build:
	cargo build

release: 
	cargo build --release

new_project:
	cargo new hello_cargo

hello:
	# use this when you want to coordinate your own build
	rustc src/hello.rs
	./hello
